export const countryLabels: Record<string, string> = {
  albania: 'Албания',
  austria: 'Австрия',
  croatia: 'Хърватия',
  'czech-republic': 'Чехия',
  greece: 'Гърция',
}

export const ui = {
  homeHeading: 'Открийте следващото си приключение',
  homeSubheading:
    'Подбрани ваканции с прозрачни цени и гъвкави дати на заминаване.',
  noTripsMatch: 'Няма екскурзии, отговарящи на филтрите.',
  clearFilters: 'Изчисти филтрите',
  filterCountry: 'Държава',
  filterByCountry: 'Филтрирай по държава',
  all: 'Всички',
  fullyBooked: 'Напълно заета',
  contactUs: 'Свържете се с нас',
  contactForAvailability: 'Свържете се с нас за наличност',
  bookNow: 'Запази сега',
  contactPageTitle: 'Контакти',
  contactHeading: 'Свържете се с нас',
  contactIntro: 'Обадете се или ни пишете - ще ви помогнем да изберете дата и да запазите място.',
  contactPhone: 'Телефон',
  contactEmail: 'Имейл',
  contactOffice: 'Или ни посетете в нашия офис',
  contactTripInquiry: (tripName: string) => `Запитване за: ${tripName}`,
  priceFrom: (price: string) => `от ${price}`,
  moreDates: (count: number) =>
    count === 1 ? '(+ още 1 дата)' : `(+ още ${count} дати)`,
  nextDeparture: (date: string) => `Следващо заминаване: ${date}`,
  allTrips: '← Всички екскурзии',
  datesAndPricing: 'Дати и цени',
  gallery: 'Галерия',
  itinerary: 'Маршрут',
  included: 'Включено',
  notIncluded: 'Не е включено',
  includedPrice: 'Включено',
  onRequest: 'По запитване',
  day: (n: number) => `Ден ${n}`,
  date: 'Дата',
  item: 'Услуга',
  price: 'Цена',
  status: 'Статус',
  available: 'Налично',
  soldOut: 'Изчерпано',
  viewPhoto: (index: number, total: number) =>
    `Преглед на снимка ${index} от ${total}`,
  photoGallery: (tripName: string) => `Галерия със снимки от ${tripName}`,
  closeGallery: 'Затвори галерията',
  previousPhoto: 'Предишна снимка',
  nextPhoto: 'Следваща снимка',
  previousGalleryPhotos: 'Предишни снимки',
  nextGalleryPhotos: 'Следващи снимки',
  switchToDark: 'Превключи на тъмен режим',
  switchToLight: 'Превключи на светъл режим',
  darkMode: 'Тъмен режим',
  lightMode: 'Светъл режим',
  mainNav: 'Основна навигация',
  navTrips: 'Ваканции',
  navContact: 'Контакти',
  openMenu: 'Отвори меню',
  closeMenu: 'Затвори меню',
} as const
