export const weekdayLabels = [
  'Понеделник',
  'Вторник',
  'Сряда',
  'Четвъртък',
  'Петък',
  'Събота',
  'Неделя',
] as const

export const countryLabels: Record<string, string> = {
  bulgaria: 'България',
  greece: 'Гърция',
  turkey: 'Турция',
}

export const ui = {
  homeHeading: 'Открийте следващото си приключение',
  homeSubheading:
    'Подбрани ваканции с прозрачни цени и гъвкави дати на заминаване.',
  noTripsMatch: 'Няма екскурзии, отговарящи на филтрите.',
  clearFilters: 'Изчисти филтрите',
  clear: 'Изчисти',
  filterCountry: 'Държава',
  filterByCountry: 'Филтрирай по държава',
  filterPrice: 'Цена',
  filterByPrice: 'Филтрирай по цена',
  filterDuration: 'Продължителност',
  filterByDuration: 'Филтрирай по продължителност',
  filterCategory: 'Категория',
  filterByCategory: 'Филтрирай по категория',
  filterDiscount: 'Оферти',
  filtersHeading: 'Филтри',
  all: 'Всички',
  fullyBooked: 'Напълно заета',
  contactUs: 'Свържете се с нас',
  contactForAvailability: 'Свържете се с нас за наличност',
  bookNow: 'Запази сега',
  contactPageTitle: 'Контакти',
  contactHeading: 'Свържете се с нас',
  contactIntro: 'Обадете се или ни пишете - ще ви помогнем да изберете дата и да запазите място.',
  contactPhone: 'Телефон',
  contactEmail: 'Имейл',
  contactOffice: 'Или ни посетете в нашия офис',
  contactWorkingHours: 'Работно време',
  contactBankName: 'Банка',
  contactIban: 'IBAN',
  contactAccountHolder: 'Титуляр',
  contactBookingLink: 'Условия за записване',
  contactTripInquiry: (tripName: string) => `Запитване за: ${tripName}`,
  moreDates: (count: number) =>
    count === 1 ? '(+ още 1 дата)' : `(+ още ${count} дати)`,
  nextDeparture: (date: string) => `Следващо заминаване: ${date}`,
  allTrips: '← Всички екскурзии',
  datesAndPricing: 'Дати и цени',
  gallery: 'Галерия',
  itinerary: 'Маршрут',
  included: 'Включено',
  notIncluded: 'Не е включено',
  includedPrice: 'Включено',
  onRequest: 'По запитване',
  day: (n: number) => `Ден ${n}`,
  date: 'Дата',
  item: 'Услуга',
  price: 'Цена',
  status: 'Статус',
  available: 'Налична',
  lastSpots: 'Последни места',
  soldOut: 'Изчерпано',
  completed: 'Приключила',
  viewPhoto: (index: number, total: number) =>
    `Преглед на снимка ${index} от ${total}`,
  photoGallery: (tripName: string) => `Галерия със снимки от ${tripName}`,
  closeGallery: 'Затвори галерията',
  previousPhoto: 'Предишна снимка',
  nextPhoto: 'Следваща снимка',
  previousGalleryPhotos: 'Предишни снимки',
  nextGalleryPhotos: 'Следващи снимки',
  switchToDark: 'Превключи на тъмен режим',
  switchToLight: 'Превключи на светъл режим',
  darkMode: 'Тъмен режим',
  lightMode: 'Светъл режим',
  mainNav: 'Основна навигация',
  navTrips: 'Ваканции',
  navContact: 'Контакти',
  navBooking: 'Как да резервирам',
  suggestedTrips: (country: string) => `Още от ${country}`,
  openMenu: 'Отвори меню',
  closeMenu: 'Затвори меню',
} as const
